jobs:

  - name: sample_scriptpub_runCI
    type: runCI
    steps:
      - IN: sample_scriptpub_ciRepo
  
  - name: sample_scriptpvt_runCI
    type: runCI
    steps:
      - IN: sample_scriptpvt_ciRepo
  
  - name: runci-nod_runCI
    type: runCI
    steps:
      - IN: runci-nod_ciRepo
      - IN: runSh-5
      - IN: runSh-6
      - IN: spvt-tg13
  
  - name: runci-jav_runCI
    type: runCI
    steps:
      - IN: runci-jav_ciRepo
      - IN: spvt-tg17
  
  - name: runci-go_runCI
    type: runCI
    steps:
      - IN: runci-go_ciRepo
  
 # - name: runci-php_runCI
   # type: runCI
   # steps:
   #   - IN: runci-php_ciRepo
  
 # - name: runci-php_runCI
 #   type: runCI
 #   steps:
 #     - IN: runci-php_ciRepo
  
 # - name: runci-clo_runCI
 #   type: runCI
 #   steps:
  #    - IN: runci-clo_ciRepo
      
  - name: release1
    type: release
    allowPublicAccess: true
    steps:
      - IN: version-rc
      - TASK: managed
        bump: rc
   
  - name: release2
    type: release
    steps:
      - IN: release1
      - TASK: managed
        bump: major
      
#MANIFESTS
      
  - name: manifest-1bb
    type: manifest
    steps:
      - IN: image1
      # versionNumber: 100
      - IN: spvt-tg1
       
  - name: manifest-2bb
    type: manifest
    steps:
      - IN: image2
      - IN: spvt-tg2
  
  - name: manifest-3bb
    type: manifest
    steps:
      - IN: image3
      - IN: manifest-1bb
      - IN: manifest-2bb
      - IN: spvt-tg3
       
#DEPLOY  
  - name: ddcdeploy-1bb
    type: deploy
    steps:
      - IN: ddccluster
      - IN: manifest-1bb
      - IN: spvt-replica2
      - IN: spvt-tg4
      
  - name: ddcdeploy-2bb
    type: deploy
    steps:
      - IN: ddccluster
      - IN: manifest-3bb       
      - IN: spvt-tg5
      
#RUNSH      
  - name: runSh-1
    type: runSh
    steps:
      - IN: scriptpvt_master
     # versionName: testsha
      - IN: param1
      - IN: spvt-tg6
      - TASK:
        - script: ls
        - script: ./IN/scriptpvt_master/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
      
  - name: runSh-2
    type: runSh
    steps:
      - IN: scriptpvt_cli1
      - IN: param2
      - IN: spvt-tg7
      - TASK:
        - script: ls
        - script: ./IN/scriptpvt_cli1/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
  
  - name: runSh-3
    type: runSh
    steps:
      - IN: runSh-1
      - IN: runSh-2
      - IN: param3
      - IN: spvt-tg8
      - TASK:
        - script: ls
        - script: echo "versionyml=$versionyml"
        - script: echo "EOF!"
        
  - name: runSh-4
    type: runSh
    steps:
      - IN: scriptpvt_test
      - IN: runSh-3
      - IN: spvt-tg9
      - TASK:
        - script: ./IN/scriptpvt_test/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
   
  - name: runSh-5
    type: runSh
    steps:
      - IN: scriptpvt_test1      
      - TASK:
        - script: ls     
        - script: ./IN/scriptpvt_test1/gitRepo/echo.sh
        
  - name: runSh-6
    type: runSh
    steps:
      - IN: scriptpub_test1      
      - TASK:
        - script: ls     
        - script: ./IN/scriptpub_test1/gitRepo/echo.sh
        
#RUNSH      
  - name: runCLI-1
    type: runCLI
    steps:
      - IN: scriptpub_master
     # versionName: testsha
      - IN: param4
      - IN: spvt-tg10
      - TASK:
        - script: ls
        - script: ./IN/scriptpub_master/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
      
  - name: runCLI-2
    type: runCLI
    steps:
      - IN: scriptpub_cli1
      - IN: param5
      - IN: spvt-tg11
      - TASK:
        - script: ls
        - script: ./IN/scriptpub_cli1/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
  
  - name: runCLI-3
    type: runCLI
    steps:
      - IN: runCLI-1
      - IN: runCLI-2
      - IN: param6
      - IN: spvt-tg12
      - TASK:
        - script: ls
        - script: echo "versionyml=$versionyml"
       # - script: sleep 2m
        - script: echo "EOF!"

        
  - name: runCLI-4
    type: runCLI
    steps:
      - IN: scriptpub_test
      - IN: runCLI-3
      - IN: spvt-tg14
      - TASK:
        - script: ./IN/scriptpub_test/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"  
  
  - name: runCLI-5
    type: runCLI
    steps:
      - IN: scriptpub_cli2
      - IN: param7
      - IN: spvt-tg15
      - TASK:
        - script: ls
        - script: ./IN/scriptpub_cli2/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
  
  - name: runCLI-6
    type: runCLI
    steps:
      - IN: scriptpvt_cli2
      - IN: param8
      - IN: runci-jav_runCI
      - IN: runCLI-5
      - IN: spvt-tg16
      - TASK:
        - script: ls
        - script: ./IN/scriptpvt_cli2/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"

  - name: runCLI-7
    type: runCLI
    steps:
      - IN: scriptpvt_test2
      - IN: param9
      - IN: runci-go_runCI
      - IN: spvt-tg17
      - TASK:
        - script: ls
        - script: ./IN/scriptpvt_test2/gitRepo/echo.sh
        - script: echo "versionyml=$versionyml"
        
        