triggers:
   - name: spvt-tg1
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg2
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg3
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg4
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg5
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg6
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg7
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg8
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg9
     type: trigger
     version:
       counter: 0

   
   - name: spvt-tg10
     type: trigger
     version:
       counter: 1
       
   - name: spvt-tg11
     type: trigger
     version:
       counter: 1
       
   - name: spvt-tg12
     type: trigger
     version:
       counter: 3
       
   - name: spvt-tg13
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg14
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg15
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg16
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg17
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg18
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg19
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg20
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg21
     type: trigger
     version:
       counter: 0
       