triggers:
   - name: spvt-tg1
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg2
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg3
     type: trigger
     version:
       counter: 0
       
  - name: spvt-tg4
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg5
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg6
     type: trigger
     version:
       counter: 0
       
  - name: spvt-tg7
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg8
     type: trigger
     version:
       counter: 0
       
   - name: spvt-tg9
     type: trigger
     version:
       counter: 0
       